[package]
name = "dsa_rust"
version = "0.1.0"
edition = "2021"
authors = ["renatodinizc <https://github.com/renatodinizc>"]

[lib]
name = "dsa_rust"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
